# Generated by Django 4.2.11 on 2024-06-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_backend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='backend',
            field=models.CharField(default='', max_length=100),
        ),
    ]
