# Generated by Django 4.2.11 on 2024-06-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_backend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='backend',
        ),
    ]
