# Generated by Django 4.2.11 on 2024-05-13 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзины', 'verbose_name_plural': 'Корзины'},
        ),
    ]
