# Generated by Django 4.2.11 on 2024-05-22 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_alter_gallery_options_sizes_slug_and_more'),
        ('carts', '0003_alter_cart_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.variants', verbose_name='Продукт'),
        ),
    ]
