# Generated by Django 4.2.11 on 2024-05-22 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_alter_gallery_options_sizes_slug_and_more'),
        ('carts', '0005_remove_cart_product_variant_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.products', verbose_name='Продукт'),
        ),
    ]
