# Generated by Django 4.2.11 on 2024-05-23 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_alter_gallery_options_sizes_slug_and_more'),
        ('carts', '0007_cart_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.variants', verbose_name='Продукт'),
        ),
    ]
