# Generated by Django 4.2.11 on 2024-05-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_alter_cart_product_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
