# Generated by Django 4.2.11 on 2024-04-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_products_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='new',
        ),
    ]
