# Generated by Django 4.2.11 on 2024-05-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelTable(
            name='gallery',
            table='gallery',
        ),
    ]
