# Generated by Django 4.2.11 on 2024-05-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_products_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='article',
            field=models.CharField(max_length=50, unique=True, verbose_name='Артикул'),
        ),
    ]
