# Generated by Django 4.2.11 on 2024-05-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_alter_gallery_options_sizes_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
    ]
