# Generated by Django 4.2.11 on 2024-06-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_product_orderitem_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'В обработке'), ('2', 'Оформлен'), ('3', 'Готов к получению')], default='1', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
