# Generated by Django 4.2.11 on 2024-06-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Комментарий к заказу'),
        ),
    ]
