# Generated by Django 4.2.11 on 2024-06-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Принят', 'Принят'), ('В обработке', 'В обработке'), ('Подтвержден', 'Подтвержден'), ('Заказ в сборке', 'Заказ в сборке'), ('Ожидание отправки', 'Ожидание отправки'), ('Доставляется', 'Доставляется'), ('Готов к получению', 'Готов к получению'), ('Отменен', 'Отменен'), ('Возврат', 'Возврат')], default='Принят', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
